"""num comments in submission

Revision ID: 57d7e4917307
Revises: d9a99f5d23ad
Create Date: 2025-02-07 00:27:06.028359

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57d7e4917307'
down_revision: Union[str, None] = 'd9a99f5d23ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submission', sa.Column('num_comments', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('submission', 'num_comments')
    # ### end Alembic commands ###
