"""unique constraints

Revision ID: d9a99f5d23ad
Revises: ac34b800d208
Create Date: 2025-02-07 00:16:23.723961

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9a99f5d23ad'
down_revision: Union[str, None] = 'ac34b800d208'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_submission_id', 'submission', ['id', 'subreddit'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_submission_id', 'submission', type_='unique')
    # ### end Alembic commands ###
